### ISSUE TITLE
System volume hud appears on screen

### ISSUE THREAD

**Issue by sasojadrovski** [gizmosachin/VolumeBar#2]
Hey @gizmosachin,

First let me thank you for this awesome custom control!

I discovered a strange bug that happens from time to time... Sometimes the System volume hud appears on the screen along with your custom VolumeBar. 

I think that this might be related to not handling the notification AVSystemController_SystemVolumeDidChangeNotification which is triggered once the system volume is changed.

I am waiting for your input on this one.

Cheers,
Sasho

**Comment by gizmosachin** [comment]
Hey @sasojadrovski, do you have an example of a case in which this occurs? I tested both device volume buttons as well as buttons on connected headphones and didn't see the system volume HUD.

**Comment by sasojadrovski** [comment]
Hello @gizmosachin 

Thanks for your fast reply, it really means a lot! 

I know it is strange, but I think that this occurs when the sound does not come from AVFoundation, i.e. from AVAudioSession.
When I use the VolumeBar while playing a video file using AVPlayer, everything works as it should, but when I display a video that comes from a video stream (I am using OpenTok), the VolumeBar displays together with the system volume HUD. 

In my code, I call the VolumeBar.sharedInstance.start() method on viewWillAppear:, and I call the VolumeBar.sharedInstance.stop() on viewWillDissapear:

Please let me know whether you need some more info, so we can resolve this one together.

Best,
Sasho

**Comment by gizmosachin** [comment]
Sorry it's taken so long for me to get back to you on this one.

Internally, `VolumeBar` uses a hidden `MPVolumeView` which hides the system volume indicator whenever an `AVAudioSession` is being used. Unfortunately, I can't find a way to hide the system volume indicator when something other than an `AVAudioSession` is being used for audio output. Closing this - sorry about that!
