### ISSUE TITLE
Crash when stop volumebar

### ISSUE THREAD

**Issue by anafinotti** [gizmosachin/VolumeBar#3]
When I enter in my screen I call start(), when I leave I call stop(), when I enter again the volumebar dont show and when I call stop() the app crashes.

Cannot remove an observer <VolumeBar.VolumeBar 0x1562beef0> for the key path "outputVolume" from <AVAudioSession 0x1562053e0> because it is not registered as an observer.'

**Comment by gizmosachin** [comment]
Hey @anafinotti, thanks so much for finding this - it should be fixed in v1.1 (see commits 727dc90a4e2c91a96b150bc04ea97674d3e8d827 and 535061677e8ef36ee56361b3049c883c1d3cd3bf). Thanks!
