### ISSUE TITLE
Touch on Top-Left of the screen shows Connecting to AirPlay devices

### ISSUE THREAD

**Issue by kennic** [gizmosachin/VolumeBar#6]
As title, touching on the Top-Left of the screen will show Connecting to AirPlay devices (I'm testing on iOS 10.2), this is not usable for player that have a "Back" button on the corner.

**Comment by gizmosachin** [comment]
Thanks @kennic! 

This should be fixed now (see https://github.com/gizmosachin/VolumeBar/commit/b24cbe7ab6d70c6834b960e7705c7680fd2d2cd5). I tested it and tapping the "Back" button in the status bar now works correctly. Please update to the latest version (2.0.2) and let me know if that fixes it.

**Comment by kennic** [comment]
Thank you, it works perfectly now!
