### ISSUE TITLE
iOS 11 crash

### ISSUE THREAD

**Issue by philipengberg** [gizmosachin/VolumeBar#9]
This line
```swift
VolumeBar.sharedInstance.start()
```
crashes on **iOS 11** only with
```
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by gizmosachin** [comment]
Thanks for reporting this @philipengberg, will look into it later today.

**Comment by gizmosachin** [comment]
I tested the sample app on an iPhone with the iOS 11 GM seed and wasn't able to reproduce the crash. @philipengberg I think this may be related to something else in your application.
